# Welcome to Jekyll!
#

# Site settings
title: |
  DEMNORM - Democratic Norms 
description: |
  What democratic norms are and how they matter   
  
  led by: [Daniel Bischof](https://www.danbischof.com)   
  funded by: [The Carlsberg Foundation](https://www.carlsbergfondet.dk/en/Forskningsaktiviteter/Bevillingsstatistik/Bevillingsoversigt/CF21_0459_Daniel-Bischof) & [Aarhus University Research Foundation](https://auff.au.dk/en/)   
owner: Daniel Bischof # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: db@danbischof.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://demnorm.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/danbischof
  github: https://github.com/demnorm
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
